[package]
name = "afterslides-py"
description = "Python bindings for afterslides."
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
afterslides.workspace = true
pyo3.workspace = true

[features]
default = ["render"]
render = ["afterslides/render"]

[lints]
workspace = true
