# Type stubs for the compiled extension. Keep in sync with crates/afterslides-py.

from typing import final

__version__: str

@final
class ShapeInfo:
    slide: int
    id: int
    name: str
    alt_text: str
    title: str
    kind: str
    placeholder_type: str | None
    placeholder_idx: int | None
    has_text: bool
    hidden: bool
    parent: int | None
    frame: tuple[int, int, int, int] | None

@final
class Presentation:
    @staticmethod
    def open(path: str) -> Presentation: ...
    @staticmethod
    def from_bytes(data: bytes) -> Presentation: ...
    def save(self, path: str) -> None: ...
    def to_bytes(self) -> bytes: ...
    def slide_size(self) -> tuple[int, int]: ...
    def slides(self) -> list[int]: ...
    def slide_index(self, slide: int) -> int: ...
    def slide_part(self, slide: int) -> str: ...
    def delete_slide(self, slide: int) -> None: ...
    def duplicate_slide(self, slide: int, position: int | None = None) -> int: ...
    def move_slide(self, slide: int, position: int) -> None: ...
    def replace_text(
        self,
        replacements: list[tuple[str, str]],
        slide: int | None = None,
        shape_id: int | None = None,
    ) -> int: ...
    def shapes(self, slide: int) -> list[ShapeInfo]: ...
    def shape_info(self, slide: int, id: int) -> ShapeInfo: ...
    def shape_text(self, slide: int, id: int) -> str | None: ...
    def set_shape_text(self, slide: int, id: int, text: str) -> None: ...
    def delete_shape(self, slide: int, id: int) -> None: ...
    def table_values(self, slide: int, id: int) -> list[list[str]]: ...
    def table_size(self, slide: int, id: int) -> tuple[int, int]: ...
    def set_table_cell_text(self, slide: int, id: int, row: int, col: int, text: str) -> None: ...
    def insert_table_row(self, slide: int, id: int, source: int, at: int) -> None: ...
    def delete_table_row(self, slide: int, id: int, row: int) -> None: ...
    def delete_table_column(self, slide: int, id: int, col: int) -> None: ...
    def fill_table(
        self, slide: int, id: int, data: list[list[str]], start_row: int, resize: bool
    ) -> None: ...
    def chart_types(self, slide: int, id: int) -> list[str]: ...
    def chart_data(
        self, slide: int, id: int
    ) -> tuple[
        list[str] | list[float] | list[list[str]],
        str,
        list[tuple[str, list[float | None], int | None, str | None]],
    ]: ...
    def set_chart_data(
        self,
        slide: int,
        id: int,
        categories: list[str] | list[float] | list[list[str]],
        series: list[tuple[str, list[float | None], int | None, str | None]],
        dates: bool = False,
    ) -> None: ...
    def chart_xy_data(
        self, slide: int, id: int
    ) -> list[tuple[str, list[float | None], list[float | None], list[float | None] | None]]: ...
    def set_chart_xy_data(
        self,
        slide: int,
        id: int,
        series: list[tuple[str, list[float | None], list[float | None], list[float | None] | None]],
    ) -> None: ...
    def chart_title(self, slide: int, id: int) -> str | None: ...
    def set_chart_title(self, slide: int, id: int, title: str) -> None: ...
